#!/bin/bash

get(){
	case $1 in
	in)	sudo apt-get install $2 ;;
	out)	sudo apt-get remove  $2 ;;
	up)	sudo apt-get update && sudo apt-get upgrade ;;
	*)	echo "USAGE: get [in|out|up] <application name>\n"
	esac
}

unzip(){

	if [ -f $1 ] ; then
		case $1 in
		*.tar.bz2)   tar xvjf $1    ;;
		*.tar.gz)    tar xvzf $1    ;;
		*.bz2)       bunzip2 $1     ;;
		*.rar)       rar x $1       ;;
		*.gz)        gunzip $1      ;;
		*.tar)       tar xvf $1     ;;
		*.tbz2)      tar xvjf $1    ;;
		*.tar.xz)    tar xpvf $1    ;;
		*.tgz)       tar xvzf $1    ;;
		*.zip)       unzip $1       ;;
		*.Z)         uncompress $1  ;;
		*.7z)        7z x $1        ;;
		*)           echo "don't know how to extract '$1'..." ;;
		esac
	else
		echo "'$1' is not a valid file!"
	fi

}

fpath(){
	for file in $(ls "$@"); do
		echo -n $(pwd)
		[[ $(pwd) != "/" ]] && echo -n /
		echo $file
	done
}


ap(){
	# auto page long files with cat pipes and line checks
	filelines=$(wc -l "$1" | cut -f 1 -d ' ')

	if [ $filelines -gt $LINES ]; then
		cat $1 | less
	else 
		cat $1
	fi
}


