#!/bin/bash

## Tar has jackass arguments, this is a simplification wrapper
## I did not want to make a script that decompressed everything because other compressioin software is very straight-forward,


# file exists?
if [ ! -f "$@" ]; then
    echo "file does not exist"
    exit
fi


case "$@" in

*.tar.bz2) tar xvjf  "$@" ;;
*.bz2)     bunzip2   "$@" ;;
*.tar.gz)  tar xvf   "$@" ;;
*.tar)     tar xvf   "$@" ;;
*.tbz2)    tar xvjf  "$@" ;;
*.tar.xz)  tar xvf   "$@" ;;
*.tgz)     tar xvzf  "$@" ;;
*)         echo "not a tar compressed file"

esac
